// This file is generated automatically by scripts/index.ts
// Do not edit this file manually

import sortClasses from './sort-classes/rule';

export default {
  'sort-classes': sortClasses
} as const;
