// This file is generated automatically by scripts/index.ts
// Do not edit this file manually

import noLiteralMustacheMix from './no-literal-mustache-mix/rule';
import sortClasses from './sort-classes/rule';

export default {
  'no-literal-mustache-mix': noLiteralMustacheMix,
  'sort-classes': sortClasses
};
