// This file is generated automatically by scripts/update.ts
// Do not edit this file manually

import atApplyRequirePostcss from './at-apply-require-postcss/rule';
import noLiteralMustacheMix from './no-literal-mustache-mix/rule';
import sortClasses from './sort-classes/rule';

export default {
  'at-apply-require-postcss': atApplyRequirePostcss,
  'no-literal-mustache-mix': noLiteralMustacheMix,
  'sort-classes': sortClasses
};
