name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun lint
      - name: Typecheck
        run: bun typecheck
      # TODO: Complete when refactored into monorepo
      # - name: Test
      #   run: bun run test:cov --watch=false
      # - name: Test e2e
      #   run: bun run --cwd e2e test:e2e --watch=false
      - name: Test build
        run: bun run build
