name: Release

on:
  push:
    branches:
      - main
permissions: {}
jobs:
  release:
    if: github.repository == 'mikededo/eslint-plugin-svelte-tailwindcss'
    permissions:
      contents: write # to create release
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -F=eslint-plugin-svelte-tailwindcss build
      - name: Capture New Release Version
        run: |
          pnpm changeset status --output=release.json
          echo "NEW_VERSION=$(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
          rm release.json
      - name: Create PR release or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
          commit: "chore(release): v${{env.NEW_VERSION}}"
          title: "chore(release): v${{env.NEW_VERSION}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
