name: Release

on:
  push:
    branches:
      - main
permissions: {}
jobs:
  release:
    if: github.repository == 'mikededo/eslint-plugin-svelte-tailwindcss'
    permissions:
      contents: write # to create release
      id-token: write # OpenID Connect token needed for provenance
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Create PR release or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun changeset version
          publish: bun changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
